package ca.mcgill.ecse.climbsafe.javafx.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import static ca.mcgill.ecse.climbsafe.javafx.controllers.ViewUtils.successful;

import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet4Controller;
import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet6Controller;

public class EquipmentPageController {
	@FXML
	private Button addButton;
	@FXML
	private TextField addEquipmentNameTextField;
	@FXML
	private TextField addWeightTextField;
	@FXML
	private TextField addCostTextField;
	@FXML
	private Button updateButton;
	@FXML
	private TextField updateEquipmentNameTextField;
	@FXML
	private TextField updateNewEquipmentNameTextField;
	@FXML
	private TextField updateWeightTextField;
	@FXML
	private TextField updateCostTextField;
	@FXML
	private Button removeButton;
	@FXML
	private TextField removeEquipmentNameTextField;

	// Event Listener on Button[#addButton].onAction
	@FXML
	public void addClicked(ActionEvent event) {
		// TODO Autogenerated
		
		try {
			String addEquipmentName = addEquipmentNameTextField.getText();
			int addWeight = Integer.parseInt(addWeightTextField.getText());
			int addCost = Integer.parseInt(addCostTextField.getText());
		    if(addEquipmentName == null || addEquipmentName.trim().isEmpty()) {
		    	ViewUtils.showError("Please input a valid equipment name");
		    } else {
		    	if (successful(() -> ClimbSafeFeatureSet4Controller.addEquipment(addEquipmentName, addWeight, addCost))) {
		    		addEquipmentNameTextField.setText("");
		    	}
		    }
		} catch(RuntimeException e){
			ViewUtils.showError(e.getMessage());
			
		}
	}
	// Event Listener on Button[#updateButton].onAction
	@FXML
	public void updateClicked(ActionEvent event) {
		// TODO Autogenerated
		
		try {
			String updateEquipmentName = updateEquipmentNameTextField.getText();
			String updateNewEquipmentName = updateNewEquipmentNameTextField.getText();
			int updateWeight = Integer.parseInt(updateWeightTextField.getText());
			int updateCost = Integer.parseInt(updateCostTextField.getText());
			if(updateEquipmentName == null || updateEquipmentName.trim().isEmpty()) {
				ViewUtils.showError("Please input valid equipment name");
			} 
			if(updateNewEquipmentName == null || updateNewEquipmentName.trim().isEmpty()) {
				ViewUtils.showError("Please input valid new equipment name");
			}
			else {
				if(successful(() -> ClimbSafeFeatureSet4Controller.updateEquipment(updateEquipmentName, updateNewEquipmentName, updateWeight, updateCost))) {
					updateEquipmentNameTextField.setText("");
					updateNewEquipmentNameTextField.setText("");
				}
			}
		} catch(RuntimeException e) {
			ViewUtils.showError(e.getMessage());
		}
	}
	// Event Listener on Button[#removeButton].onAction
	@FXML
	public void removeClicked(ActionEvent event) {
		// TODO Autogenerated
		
		try {
			String removeEquipmentName = removeEquipmentNameTextField.getText();
			if(removeEquipmentName == null || removeEquipmentName.trim().isEmpty()) {
				ViewUtils.showError("Please input valid equipment name");
			} else {
				if(successful(() -> ClimbSafeFeatureSet6Controller.deleteEquipment(removeEquipmentName)));
				removeEquipmentNameTextField.setText("");
			}
		} catch(RuntimeException e) {
			ViewUtils.showError(e.getMessage());
		}
	}
}
