package ca.mcgill.ecse.climbsafe.javafx.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.sql.Date;
import java.time.LocalDate;
import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet1Controller;
import ca.mcgill.ecse.climbsafe.controller.InvalidInputException;
import javafx.event.ActionEvent;

import javafx.scene.control.DatePicker;

public class Setup_NMCController {
	@FXML
	private Button UpdateAdmin;
	@FXML
	private TextField NumberWeeks;
	@FXML
	private TextField GuidePrice;
	@FXML
	private DatePicker StartDate;
	
	@FXML
	public void initialize() {
		DatePicker datePicker = new DatePicker();
		datePicker.setEditable(false);
		datePicker.setValue(LocalDate.now());
	}
	// Event Listener on Button[#UpdateAdmin].onAction
	@FXML
	public void clickUpdateAdmin(ActionEvent event) {
		// TODO Autogenerated
		try {
			ClimbSafeFeatureSet1Controller.setup(Date.valueOf(StartDate.getValue()), Integer.parseInt(NumberWeeks.getText()), Integer.parseInt(GuidePrice.getText()));
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			ViewUtils.showError(e.getMessage());
		} catch (InvalidInputException e) {
			// TODO Auto-generated catch block
			ViewUtils.showError(e.getMessage());
		}
        NumberWeeks.setText("");
        GuidePrice.setText("");
	}
}

