package ca.mcgill.ecse.climbsafe.javafx.pages;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.chart.PieChart;
import javafx.scene.chart.PieChart.Data;
import javafx.scene.chart.LineChart;
import ca.mcgill.ecse.climbsafe.controller.ClimbSafeBonusFeaturesController;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

public class BonusFeaturesController {
	@FXML
	private PieChart Pie;
	@FXML
	private Button PieChart;
	@FXML
	private LineChart GraphMember;
	@FXML
	private Button updateGraph;

	// Event Listener on Button[#PieChart].onAction
	@FXML
	public void clickUpdatePieChart(ActionEvent event) {
		// TODO Autogenerated
		try {
			ObservableList<Data> a = ClimbSafeBonusFeaturesController.getMemberStats();
			Pie.setData(a);
		} catch(Exception e) {
			System.out.println("oh no!");
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#updateGraph].onAction
	@FXML
	public void clickUpdateGraph(ActionEvent event) {
		// TODO Autogenerated
	}
}
