/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.climbsafe.application;

import java.sql.Date;
import java.time.LocalDate;
import ca.mcgill.ecse.climbsafe.javafx.ClimbSafeFxmlView;
import ca.mcgill.ecse.climbsafe.model.ClimbSafe;
import ca.mcgill.ecse.climbsafe.persistence.ClimbSafePersistence;
import javafx.application.Application;

public class ClimbSafeApplication {
  private static ClimbSafe climbSafe;
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    //System.out.println(new ClimbSafeApplication().getGreeting());
    Application.launch(ClimbSafeFxmlView.class, args);
  }

  public static ClimbSafe getClimbSafe() {
    if (climbSafe == null) {
      // these attributes are default, you should set them later with the setters
      climbSafe = ClimbSafePersistence.load();
    }
    
    return climbSafe;
  }
 
}