package ca.mcgill.ecse.climbsafe.javafx.fxml.pages;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Tab;

import javafx.event.Event;

public class Setup_NMCController {
	@FXML
	private Tab AdminTab;
	@FXML
	private Button updateButton1;
	@FXML
	private Button updateButton2;
	@FXML
	private TextField AdminEmail;
	@FXML
	private TextField AdminPassword;
	@FXML
	private TextField SeasonStart;
	@FXML
	private TextField SeasonEnd;
	@FXML
	private TextField GuidePrice;
	@FXML
	private TextField MemberEmail;
	@FXML
	private TextField MemberAssignedWeeks;

	// Event Listener on Tab[#AdminTab].onSelectionChanged
	@FXML
	public void clickedAdminTab(Event event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateButton1].onAction
	@FXML
	public void updateClicked1(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateButton2].onAction
	@FXML
	public void clickedupdateButton2(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#AdminEmail].onAction
	@FXML
	public void enterAdminEmail(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#AdminPassword].onAction
	@FXML
	public void enterAdminPassword(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#SeasonStart].onAction
	@FXML
	public void enterSeasonStart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#SeasonEnd].onAction
	@FXML
	public void enterSeasonEnd(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#GuidePrice].onAction
	@FXML
	public void enterGuidePrice(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#MemberEmail].onAction
	@FXML
	public void enterMemberEmail(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#MemberAssignedWeeks].onAction
	@FXML
	public void enterMemberAssignedWeeks(ActionEvent event) {
		// TODO Autogenerated
	}
}
